### ISSUE TITLE
Database for Member and Project Management

### ISSUE THREAD

**Issue by AryanVBW** [NST-SDC/DevClub-Site#8]
<p align="center">
<img src="https://github.com/nst-sdc/DevCoin/releases/download/l1/Designer-bg.png" height="300">
</p>

# Database for Member and Project Management

## Problem

We need a way to store and easily access information about our club members, including their names, portfolios, current projects, email addresses, and other relevant details. This will help us streamline project management and communication, especially as our club grows and we take on new initiatives.

## Proposed Solution

Create a database (consider options like SQLite, PostgreSQL, or MongoDB depending on your needs and preferences) to store member information. This database should include fields for:

* **Member Name**
* **Email Address**
* **Portfolio Link**
* **Current Project(s)** (potentially with details like project description, role, technologies used)
* **Other relevant details** (e.g., skills, interests, graduation year, etc.)

## Benefits

* **Easy Member Management:** Quickly find and update member information.
* **Project Organization:** Keep track of who's working on what.
* **Improved Communication:**  Easily contact members with project updates or club announcements.
* **Streamlined Onboarding:**  Efficiently add new members and their information. 

## Tasks

- [ ] Choose a database technology.
- [ ] Design the database schema (tables and fields).
- [ ] Implement the database in the backend.
- [ ] Develop an interface (e.g., admin panel) to manage the data.
- [ ] Integrate the database with the website's functionality.

# ✨ DevCoins: Your Key to Awesome Rewards! ✨

Earn DevCoins by contributing to NST-SDC and unlock a treasure trove of digital tools, resources, and exclusive goodies!

**Power Up Your Development Journey:**

* **Top-tier IDEs:**  Get access to powerful Integrated Development Environments (IDEs) like JetBrains and GitHub Codespaces to code like a pro! 
* **Cloud Computing:**  Harness the power of the cloud with credits for platforms like DigitalOcean, Microsoft Azure, and Heroku to build and deploy your projects.
* **Database Prowess:**  Master databases with credits for platforms like MongoDB Atlas.
* **Design & Collaboration:**  Create stunning visuals and collaborate effectively with tools like Canva.
* **Domain Names:**  Secure your own domain name and build your online presence.

**And that's not all!**

* **Exclusive Swag:**  Redeem your DevCoins for cool NST-SDC merchandise like t-shirts, stickers, and more.
* **Unique Badges:**  Show off your achievements and contributions with custom digital badges.
* **Priority Access:**  Get early access to workshops, events, and mentorship opportunities.

**How to Earn DevCoins?**

* Contribute to projects 🧑‍💻
* Participate in events 🤝
* Share your knowledge 🧠
* Be an active member! 🙌

**Start earning and unlock a world of possibilities with DevCoins!** 🚀
